version: '3.9'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks: 
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/nechaara/data/mysql
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/nechaara/data/wordpress
      o: bind
