services:
  mariadb:
    container_name: "mariadb"
    ports: "3306:3306"
    restart: "always"

  nginx:
    container_name: "nginx"
    depends_on: "wordpress"
    ports: "443:443"
    restart: "always"
    
  wordpress:
    container_name: "wordpress"
    depends_on: "nginx"
    ports: "9000:9000"
    restart: "always"


