networks:
  inception_nt:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build : ./requirements/mariadb
    restart: always
    networks: [inception_nt]

  nginx:
    container_name: nginx
    build : ./requirements/nginx
    depends_on: 
      - wordpress
    restart: always
    networks: [inception_nt]
    ports: ["443:443"]
    
  wordpress:
    container_name: "wordpress"
    build : ./requirements/wordpress
    depends_on: 
      - mariadb
    restart: always
    networks: [inception_nt]

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/nechaara/volumes/mysql
      o: bind
  
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/nechaara/volumes/wordpress
      o: bind

